---
- name: Copy app and starting app
  hosts: app
  remote_user: ubuntu

  tasks:
  - name: Copying file with 
    copy:
        src: /var/lib/jenkins/workspace/final_project/app.jar
        dest: /home/ubuntu/

  - name: Update apt packages
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Install openjdk
    apt: name=openjdk-8-jre state=latest

  - name: Stop jar
    shell: nohup java -jar /home/ubuntu/app.jar stop &

  - name: Start jar
    shell: nohup java -jar /home/ubuntu/app.jar &