---
- name: Copy app and starting app
  hosts: app
  become: yes

  tasks:
  - name: Copying app file 
    copy:
        src: /var/lib/jenkins/workspace/final_project/app.jar
        dest: /home/user/

  - name: Stop jar
    shell: nohup java -jar /home/user/app.jar stop &

  - name: Start jar
    shell: nohup java -jar /home/user/app.jar &
  