---
- name: Copy app and starting app
  sudo: yes
  hosts: app
  become: yes

  tasks:
  - name: Updates apt cache
    action: apt update_cache=true

  - name: Install openjdk
    apt: name=openjdk-8-jre state=latest
    become: yes

  - name: Copying file with 
    become: true 
    copy:
        src: /var/lib/jenkins/workspace/final_project/app.jar
        dest: /home/user/

  - name: Stop jar
    shell: nohup java -jar /home/user/app.jar stop &

  - name: Start jar
    shell: nohup java -jar /home/user/app.jar &
  