---
- name: Copy app and starting app
  hosts: app
  become: yes

  tasks:
  - name: Install openjdk
    apt: name=openjdk-8-jre state=latest

  - name: Copying app file 
    copy:
        src: /var/lib/jenkins/workspace/final_project/app.jar
        dest: /home/ubuntu/

  - name: Stop jar
    shell: nohup java -jar /home/ubuntu/app.jar stop &

  - name: Start jar
    shell: nohup java -jar /home/ubuntu/app.jar &
  