---
- name: Copy app and starting app
  hosts: app
  become: yes

  tasks:
  - name: Install openjdk
    apt: name=openjdk-8-jre state=latest
    update_cache: yes
    become: yes

  - name: Copying file with 
    become: true 
    copy:
        src: /var/lib/jenkins/workspace/final_project/app.jar
        dest: /home/user/

  - name: Stop jar
    shell: nohup java -jar /home/user/app.jar stop &

  - name: Start jar
    shell: nohup java -jar /home/user/app.jar &
  