---
- name: Install Docker and Starting app
  hosts: app
  become: yes
    
  tasks:
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      cache_valid_time: 86400 
  
  - name: Install Docker
    apt: name=docker.io state=latest

  - name: Add user to docker group
    command: "sudo gpasswd -a $USER docker"
    
  - name: Ensure python3-docker package is installed
    apt:
        name: python3-docker
        state: present
        update_cache: True

  - name: Start a container
    command: "docker run -d --rm -p 8080:8080 taruraiev/petclinic:latest"